### PR TITLE
updating README-ko file

### PR DESCRIPTION
**Pull request by hisunah**

### CODE REVIEW

**Comment by hisunah** [comment]
accidently did pull request incorrectly. will do again.

**Review by stevemar — APPROVED** [review]
i'm good with this

**Comment by stevemar** [comment]
@hisunah i think this is fine to merge now, did you want to make additional edits? I can merge it once you confirm.

**Comment by hisunah** [comment]
@stevemart  Please go ahead and merge this PR. Thanks for this sports buddy TJbot journey :)

**Comment by stevemar** [comment]
thanks for confirming @hisunah, and you're welcome :)

**Pull request merged**
